name: Eslint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies 
        run: npm ci

      - name: Run eslint
        run: eslint .